#!/usr/bin/env python

import sys, signal, subprocess

colorizedSubcommands = (
	'status', 'stat', 'st',
	'add',
	'delete', 'del', 'remove', 'rm',
    'move', 'mv', 'rename', 'ren'
)

statusColors = {
    'M'     : "31",     # red
    '?'     : "37",     # grey
    'A'     : "32",     # green
    # 'X'     : "36",     # yellow
    'C'     : "30;41",  # black on red
    'D'     : "31",   # bold red
    '-'     : "31",     # red
    '+'     : "32",     # green
}

def colorize(line):
    if type(line) == bytes:
        line = line.decode()
    for status in statusColors:
        if line.startswith(status):
            return ''.join(("\033[", statusColors[status], "m", line, "\033[0m"))
    else:
        return line

def signal_handler(sig, frame):
    sys.exit(1)

if __name__ == '__main__':
    command = sys.argv
    command[0] = '/usr/bin/svn'

    if len(command) > 1:
        subcommand = (command[1], '')[len(command) < 2]
    else:
        subcommand = ''
    if subcommand in colorizedSubcommands and sys.stdout.isatty():
        task = subprocess.Popen(command, stdout=subprocess.PIPE)
        while True:
            line = task.stdout.readline()
            if not line:
                break
            sys.stdout.write(colorize(line))
            sys.stdout.flush()
    else:
        task = subprocess.Popen(command)

    signal.signal(signal.SIGINT, signal_handler)
    task.communicate()
    sys.exit(task.returncode)

