# 此类配置可以在命令行模式中输入show-options -g查询
set -g base-index 1                        # 窗口的初始序号; 默认为0, 这里设置为1
set -g display-time 3000                   # 提示信息的持续时间; 设置足够的时间以避免看不清提示, 单位为毫秒
set -g display-panes-time 3000
set -g repeat-time 1000                    # 控制台激活后的持续时间; 设置合适的时间以避免每次操作都要先激活控制台, 单位为毫秒
set -g allow-rename off                    # 关闭窗口自动重命名
set -g default-terminal "screen-256color"  # 支持256色显示

# 此类设置可以在命令行模式中输入show-window-options -g查询
setw -g pane-base-index 1                  # pane的初始序号; 默认为0, 这里设置为1
setw -g mode-keys vi                       # 复制模式中的默认键盘布局; 可以设置为vi或emacs
setw -gq utf8 on                           # 开启窗口的UTF-8支持
setw -gq mode-mouse off                    # 窗口切换后让人可以用鼠标上下滑动显示历史输出(影响XSHELL的选中复制, 所以OFF)

# Changing the default prefix key
# set -g prefix C-a
# unbind-key C-b
# bind-key C-a send-prefix

# 窗口切分快捷键(1.9以上版本增加参数 -c '#{pane_current_path}')
bind 'c' new-window -c '#{pane_current_path}'
bind '-' split-window -v -c '#{pane_current_path}'
bind '\' split-window -h -c '#{pane_current_path}'
bind 'K' confirm-before -p 'kill pane #{pane_index} [#{pane_current_path}]? (y/n)' kill-pane

# Pane之间切换的快捷键
bind 'k' select-pane -U    # 上方窗口
bind 'j' select-pane -D    # 下面窗口
bind 'h' select-pane -L    # 左边窗口
bind 'l' select-pane -R    # 右边窗口

# Pane布局切换
unbind Space
bind Space if-shell "tmux display-message -p '#{window_layout}' | grep -q '{'" "selectl even-vertical" "selectl even-horizontal"

# Copy Mode
bind 'u' copy-mode
bind C-u copy-mode -u

#===========================================================
# 状态栏
#===========================================================
# 颜色 black, red, green, yellow, blue, magenta, cyan, white, '#FFFFFF'
set -g status-bg '#303030'
set -g status-fg white

# 操作状态栏时的默认键盘布局; 可以设置为vi或emacs
set -g status-keys vi

# 开启状态栏的UTF-8支持
set -gq status-utf8 on

# 对齐方式
set -g status-justify centre

# 左下角
set -g status-left '#[fg=green][#[fg=cyan]#S#[fg=green]]'
set -g status-left-length 30

# 窗口列表
setw -g automatic-rename on
setw -g window-status-format '#[dim]#I:#[default]#W#[fg=grey,dim]'
setw -g window-status-current-format '#[fg=cyan,bold]#I#[fg=blue]:#[fg=cyan]#W#[fg=dim]'

# 右下角
set -g status-right '#[fg=green][#[fg=cyan]%a %H:%M %m-%d#[fg=green]]'

# 回溯缓冲区大小
set -g history-limit 10240

